version: "3"

services:
  concourse:
    image: concourse/concourse:7.0.0
    command: "quickstart"
    ports:
      - "8080:8080"
    privileged: true
    environment:
      - CONCOURSE_POSTGRES_HOST=db
      - CONCOURSE_POSTGRES_USER=concourse
      - CONCOURSE_POSTGRES_PASSWORD=password
      - CONCOURSE_POSTGRES_DATABASE=concourse
      - CONCOURSE_EXTERNAL_URL=http://localhost:8080
      - CONCOURSE_ADD_LOCAL_USER=user:password
      - CONCOURSE_MAIN_TEAM_LOCAL_USER=user
  db:
    image: postgres:13.2
    environment:
      - POSTGRES_USER=concourse
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=concourse
