version: "2.4"

services:
  server:
    image: gocd/gocd-server:v19.2.0
    volumes:
      - ./server/config:/godata/config
    ports:
      - "8153:8153"

  agent:
    image: gocd/gocd-agent-alpine-3.9:v19.2.0
    restart: unless-stopped
    volumes:
      - ./scripts:/scripts
    environment:
      GO_SERVER_URL: "http://server:8153/go"
      AGENT_AUTO_REGISTER_KEY: "ab455494-52a3-4ce7-b0cc-d38fbdc0aea9"
